/**
 * Commit & Secure Hall of Fame - Script
 *
 * This file fetches contributor data from data.json (generated by the CI pipeline),
 * then handles rendering cards, filtering by theme, searching by name/username,
 * and animating statistics counters.
 *
 * data.json is generated automatically by scripts/generate_hall_of_fame.py
 * whenever a contributor's Pull Request is merged.
 */

document.addEventListener('DOMContentLoaded', () => {
    // -------------------------------------------------
    // DOM Elements — these IDs must match index.html
    // -------------------------------------------------
    const grid = document.getElementById('contributors-grid');
    const searchInput = document.getElementById('search-input');
    const filterBtns = document.querySelectorAll('.filter-btn');
    const statContributors = document.getElementById('stat-contributors');
    const statBadges = document.getElementById('stat-badges');

    // -------------------------------------------------
    // Application State
    // -------------------------------------------------
    let contributors = [];       // All contributors loaded from data.json
    let currentFilter = 'all';   // Currently selected theme filter
    let currentSearch = '';      // Current search query

    // -------------------------------------------------
    // Load Data — fetch data.json on page load
    // -------------------------------------------------
    fetch('data.json')
        .then(response => {
            if (!response.ok) {
                throw new Error('data.json not found');
            }
            return response.json();
        })
        .then(data => {
            contributors = data;
            renderCards();
            updateStats();
        })
        .catch(error => {
            // If data.json doesn't exist yet (no contributors have been merged),
            // show a friendly empty state message instead of an error
            console.log('No contributor data available yet:', error.message);
            if (grid) {
                grid.innerHTML = `
                    <div style="text-align: center; grid-column: 1 / -1; color: var(--text-muted, #888); padding: 3rem;">
                        <h3 style="margin-bottom: 0.5rem;">🚀 No contributors yet!</h3>
                        <p>Be the first to join the Hall of Fame by completing the workshop and submitting a Pull Request.</p>
                    </div>`;
            }
        });

    // -------------------------------------------------
    // Event Listeners — search and filter buttons
    // -------------------------------------------------

    // Search: filter cards as the user types
    if (searchInput) {
        searchInput.addEventListener('input', (e) => {
            currentSearch = e.target.value;
            renderCards();
        });
    }

    // Theme filter buttons: click to filter by theme
    filterBtns.forEach(btn => {
        btn.addEventListener('click', () => {
            // Update active button styling
            filterBtns.forEach(b => b.classList.remove('active'));
            btn.classList.add('active');

            // Update the filter and re-render
            currentFilter = btn.dataset.theme;
            renderCards();
        });
    });

    // -------------------------------------------------
    // renderCards — builds the contributor card grid
    // -------------------------------------------------
    function renderCards() {
        if (!grid) return;

        grid.innerHTML = '';

        // Apply search and theme filters
        const filtered = contributors.filter(c => {
            const matchesTheme = currentFilter === 'all' || c.theme === currentFilter;
            const searchLower = currentSearch.toLowerCase();
            const matchesSearch = c.name.toLowerCase().includes(searchLower) ||
                                  c.github.toLowerCase().includes(searchLower);
            return matchesTheme && matchesSearch;
        });

        // Show empty state if no results
        if (filtered.length === 0) {
            grid.innerHTML = `<div style="text-align: center; grid-column: 1 / -1; color: var(--text-muted, #888); padding: 3rem;">
                No contributors found matching your criteria.
            </div>`;
            return;
        }

        // Create a card for each contributor
        filtered.forEach((contributor, index) => {
            const card = document.createElement('div');
            card.className = 'card';
            // Staggered entrance animation
            card.style.transitionDelay = `${index * 50}ms`;

            // Badge link (if badge field exists in data.json)
            const badgeLink = contributor.badge
                ? `<a href="${contributor.badge}" class="badge-link" target="_blank" rel="noopener noreferrer" title="View Badge">🎖️ Badge</a>`
                : '';

            card.innerHTML = `
                <div class="card-header">
                    <div class="card-title">
                        <h3>${contributor.name}</h3>
                        <a href="https://github.com/${contributor.github}" target="_blank" rel="noopener noreferrer">@${contributor.github}</a>
                    </div>
                    <div class="badge">✓ Secured</div>
                </div>
                <div class="theme-tag ${contributor.theme}">
                    ${contributor.theme} Theme
                </div>
                <div class="card-footer">
                    <a href="${contributor.website}" class="btn" target="_blank" rel="noopener noreferrer">View Profile</a>
                    ${badgeLink}
                </div>
            `;

            grid.appendChild(card);

            // Trigger CSS entrance animation after a brief delay
            setTimeout(() => {
                card.classList.add('visible');
            }, 10);
        });
    }

    // -------------------------------------------------
    // updateStats — animate the stats counters
    // -------------------------------------------------
    function updateStats() {
        const total = contributors.length;
        // All contributors in data.json have completed: true,
        // so badges earned equals total contributors
        const earned = contributors.length;

        animateValue(statContributors, 0, total, 1000);
        animateValue(statBadges, 0, earned, 1000);
    }

    // -------------------------------------------------
    // animateValue — smoothly counts a number up
    // -------------------------------------------------
    function animateValue(element, start, end, duration) {
        if (!element || end === 0) return;

        let startTimestamp = null;
        const step = (timestamp) => {
            if (!startTimestamp) startTimestamp = timestamp;
            const progress = Math.min((timestamp - startTimestamp) / duration, 1);
            element.innerHTML = Math.floor(progress * (end - start) + start);
            if (progress < 1) {
                window.requestAnimationFrame(step);
            }
        };
        window.requestAnimationFrame(step);
    }
});
